title: Nivum AI
description: Full-stack AI-powered customer engagement and conversation analysis platform.
theme: jekyll-theme-minimal
baseurl: ""
url: "https://nivumai.github.io"
platform_name: Nivum AI
github:
  is_project_page: false
  repository_url: https://github.com/nivumai/nivumai
